apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-python
  namespace: hello-python
  labels:
    app: hello-python
    managed-by: backstage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hello-python.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-python
            port:
              number: 80
