apiVersion: v1
kind: Service
metadata:
  name: hello-python
  namespace: hello-python
  labels:
    app: hello-python
    managed-by: backstage
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: hello-python
